ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
tasks:
  - before: nvm install 16
    init: npm install
    command: npm run start


vscode:
  extensions:
    - esbenp.prettier-vscode
